###
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type:application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

<> 2023-01-17T142919.200.json

###
GET {{content_host}}/content/course-category/tree-nodes

<> 2023-01-17T142923.200.json

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "CSS",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "课程介绍",
  "charge": "201001",
  "price": "10",
  "originalPrice": "10",
  "qq": "131241",
  "wechat": "4321433214",
  "phone": "5345634",
  "validDays": 365
}

<> 2023-01-17T154507.200.json
<> 2023-01-17T154046.404.json
<> 2023-01-17T153944.404.json
<> 2023-01-17T153933.404.json
<> 2023-01-17T153707.404.json

### 查询课程计划
GET {{content_host}}/content/teachplan/18/tree-nodes

### 删除课程计划
DELETE {{content_host}}/content/teachplan/113

### 查询课程教师
GET {{content_host}}/content/courseTeacher/list/74

### 添加课程教师
POST {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "courseId": 75,
  "teacherName": "王老师",
  "position": "教师职位",
  "introduction": "教师简介"
}

### 查询课程发布信息
GET {{content_host}}/content/r/coursepublish/18